config/routes.rb
Festivals::Application.routes.draw do

  resources :festivals do
    member do
      get :month
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

end

app/models/festival.rb
class Festival < ActiveRecord::Base
  attr_accessible :camping, :date, :details, :lineup, :logo, :name, :month, :url

  default_scope order: 'festivals.date ASC'
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  # GET /festivals
  # GET /festivals.json
  def index
    if params[:month]
      @festivals = Festival.find_all_by_month(params[:month])
    else
      @festivals = Festival.all

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @festivals }
    end
  end

  # GET /festivals/1
  # GET /festivals/1.json
  def show
      
    @festival = Festival.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @festival }
    end
  end

  # GET /festivals/new
  # GET /festivals/new.json
  def new
    @festival = Festival.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @festival }
    end
  end

  # GET /festivals/1/edit
  def edit
    @festival = Festival.find(params[:id])
  end

  # POST /festivals
  # POST /festivals.json
  def create
    @festival = Festival.new(params[:festival])

    respond_to do |format|
      if @festival.save
        format.html { redirect_to @festival, notice: 'Festival was successfully created.' }
        format.json { render json: @festival, status: :created, location: @festival }
      else
        format.html { render action: "new" }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /festivals/1
  # PUT /festivals/1.json
  def update
    @festival = Festival.find(params[:id])

    respond_to do |format|
      if @festival.update_attributes(params[:festival])
        format.html { redirect_to @festival, notice: 'Festival was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /festivals/1
  # DELETE /festivals/1.json
  def destroy
    @festival = Festival.find(params[:id])
    @festival.destroy

    respond_to do |format|
      format.html { redirect_to festivals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/views/festivals/_festival.html.erb
<!-- <div class="content">
	<% @festivals.each do |festival| %>
		<span class="name"><%= festival.name %> </span>

		<!-- <span class="logo"> 
			<%= link_to image_tag(festival.logo, alt: "EDC NYC 2013"), 'http://electricdaisycarnival.com/NewYork/' %>
		</span> -->
	<!-- 
	<span class="date"> <%= festival.date %> </span>
	<span class="details"> <%= festival.name %> </span> 
	<% end %>
</div> -->


<% @festivals.each do |festival| %>
 
    <span><%= festival.name %></span>
    <span><%= festival.logo %></span>
    <span><%= festival.date %></span>
    <span><%= festival.lineup %></span>
    <span><%= festival.details %></span>
    <span><%= festival.camping %></span>
    <span><%= festival.month %></span>
 <% end %>

app/views/festivals/_form.html.erb
<%= form_for(@festival) do |f| %>
  <% if @festival.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@festival.errors.count, "error") %> prohibited this festival from being saved:</h2>

      <ul>
      <% @festival.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :lineup %><br />
    <%= f.text_area :lineup %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :camping %><br />
    <%= f.check_box :camping %>
  </div>
  <div class="field">
    <%= f.label :month %><br />
    <%= f.number_field :month %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/festivals/_rsvp.html.erb
<%= form_for(festival.rsvps.find_by_id(festival.id),
             html: { method: :post }, 
             remote: true) do |f| %>
  <%= f.submit "I'm going!", class: "btn btn-large" %>
<% end %>

<%= form_for(festival.rsvps.find_by_id(festival.id), 
			html: { method: :post },
			remote: true) do |f| %>
  <div><%= f.hidden_field festival.id %></div>
  <%= f.submit "I want to go!", class: "btn btn-large" %>
<% end %>

app/views/festivals/edit.html.erb
<h1>Editing festival</h1>

<%= render 'form' %>

<%= link_to 'Show', @festival %> |
<%= link_to 'Back', festivals_path %>

app/views/festivals/index.html.erb
<div class="container">

 <div class="row-fluid">
   
      <div id="articles" class="section"> <!-- A new section with the articles -->

        <% @festivals.each do |festival| %>

            <div id="article1" class="article"> <!-- The new article tag. The id is supplied so it can be scrolled into view. -->
                <h2><%= festival.name %></h2>
                <span class="date"><%= festival.date.to_formatted_s(:long) %></span>

                <div class="line"></div>
                
                <div class="articleBody clear">
                
                    <div class="figure"> <!-- The figure tag marks data (usually an image) that is part of the article -->
                       <%= link_to image_tag(festival.logo, :alt => festival.name, :width => 620, :height => 340), festival.url %> 
                    </div> 

                    <p><div class="details"><%= festival.details %></div></p>
                    <p><div class="lineup"><h3>Lineup: </h3>
                        <% artists = festival.lineup.split(",") %>
                        <% artists.each do |artist| %>
                            <span class="lineup_artist"><%= artist %> | </span>
                        <% end %>
                    </div></p>
                    <p>
                        <%= render 'follow_form' if signed_in? %>
                    </p>
                </div>
            </div>
            
        <% end %>


    </div>
    
  </div>
<!-- 
<h1>Listing festivals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Logo</th>
    <th>Date</th>
    <th>Lineup</th>
    <th>Details</th>
    <th>Camping</th>
    <th>Month</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @festivals.each do |festival| %>
  <tr>
    <td><%= festival.name %></td>
    <td><%= festival.logo %></td>
    <td><%= festival.date %></td>
    <td><%= festival.lineup %></td>
    <td><%= festival.details %></td>
    <td><%= festival.camping %></td>
    <td><%= festival.month %></td>
    <td><%= link_to 'Show', festival %></td>
    <td><%= link_to 'Edit', edit_festival_path(festival) %></td>
    <td><%= link_to 'Destroy', festival, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table> -->

<br />

<%= link_to 'New Festival', new_festival_path %>

</div>

app/views/festivals/new.html.erb
<h1>New festival</h1>

<%= render 'form' %>

<%= link_to 'Back', festivals_path %>

app/views/festivals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @festival.name %>
</p>

<p>
  <b>Logo:</b>
  <%= @festival.logo %>
</p>

<p>
  <b>Date:</b>
  <%= @festival.date %>
</p>

<p>
  <b>Lineup:</b>
  <%= @festival.lineup %>
</p>

<p>
  <b>Details:</b>
  <%= @festival.details %>
</p>

<p>
  <b>Camping:</b>
  <%= @festival.camping %>
</p>

<p>
  <b>Month:</b>
  <%= @festival.month %>
</p>


<%= link_to 'Edit', edit_festival_path(@festival) %> |
<%= link_to 'Back', festivals_path %>